//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AttendanceSystemEntities : DbContext
    {
        public AttendanceSystemEntities()
            : base("name=AttendanceSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mst_AdminRole> mst_AdminRole { get; set; }
        public virtual DbSet<mst_CompanyType> mst_CompanyType { get; set; }
        public virtual DbSet<tbl_DynamicContent> tbl_DynamicContent { get; set; }
        public virtual DbSet<tbl_EmployeeFingerprint> tbl_EmployeeFingerprint { get; set; }
        public virtual DbSet<tbl_EmployeeRating> tbl_EmployeeRating { get; set; }
        public virtual DbSet<tbl_Feedback> tbl_Feedback { get; set; }
        public virtual DbSet<tbl_Holiday> tbl_Holiday { get; set; }
        public virtual DbSet<tbl_Leave> tbl_Leave { get; set; }
        public virtual DbSet<tbl_Material> tbl_Material { get; set; }
        public virtual DbSet<tbl_MaterialCategory> tbl_MaterialCategory { get; set; }
        public virtual DbSet<tbl_Package> tbl_Package { get; set; }
        public virtual DbSet<tbl_Site> tbl_Site { get; set; }
        public virtual DbSet<tbl_SMSPackage> tbl_SMSPackage { get; set; }
        public virtual DbSet<tbl_Sponsor> tbl_Sponsor { get; set; }
        public virtual DbSet<tbl_LoginHistory> tbl_LoginHistory { get; set; }
        public virtual DbSet<tbl_AssignWorker> tbl_AssignWorker { get; set; }
        public virtual DbSet<tbl_ContactForm> tbl_ContactForm { get; set; }
        public virtual DbSet<tbl_Testimonial> tbl_Testimonial { get; set; }
        public virtual DbSet<tbl_Attendance> tbl_Attendance { get; set; }
        public virtual DbSet<tbl_SMSContent> tbl_SMSContent { get; set; }
        public virtual DbSet<tbl_WorkerType> tbl_WorkerType { get; set; }
        public virtual DbSet<tbl_Conversion> tbl_Conversion { get; set; }
        public virtual DbSet<tbl_WorkerPayment> tbl_WorkerPayment { get; set; }
        public virtual DbSet<tbl_HomeImage> tbl_HomeImage { get; set; }
        public virtual DbSet<tbl_HomeSlider> tbl_HomeSlider { get; set; }
        public virtual DbSet<tbl_EmployeePayment> tbl_EmployeePayment { get; set; }
        public virtual DbSet<tbl_SMSLog> tbl_SMSLog { get; set; }
        public virtual DbSet<tbl_CompanyRenewPayment> tbl_CompanyRenewPayment { get; set; }
        public virtual DbSet<tbl_CompanySMSPackRenew> tbl_CompanySMSPackRenew { get; set; }
        public virtual DbSet<tbl_InvoiceLastDocNo> tbl_InvoiceLastDocNo { get; set; }
        public virtual DbSet<mst_FinancialYear> mst_FinancialYear { get; set; }
        public virtual DbSet<tbl_EmployeeBuyTransaction> tbl_EmployeeBuyTransaction { get; set; }
        public virtual DbSet<tbl_Followup> tbl_Followup { get; set; }
        public virtual DbSet<tbl_WorkerAttendance> tbl_WorkerAttendance { get; set; }
        public virtual DbSet<tbl_EmployeeLunchBreak> tbl_EmployeeLunchBreak { get; set; }
        public virtual DbSet<tbl_Setting> tbl_Setting { get; set; }
        public virtual DbSet<tbl_Country> tbl_Country { get; set; }
        public virtual DbSet<tbl_State> tbl_State { get; set; }
        public virtual DbSet<tbl_District> tbl_District { get; set; }
        public virtual DbSet<tbl_WorkerHead> tbl_WorkerHead { get; set; }
        public virtual DbSet<tbl_AdminUser> tbl_AdminUser { get; set; }
        public virtual DbSet<tbl_Company> tbl_Company { get; set; }
        public virtual DbSet<tbl_Employee> tbl_Employee { get; set; }
        public virtual DbSet<tbl_CompanyRequest> tbl_CompanyRequest { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<Usp_GetPatmentReport_Result> Usp_GetPatmentReport(Nullable<int> startMonth, Nullable<int> endMonth, Nullable<int> year, Nullable<long> employeeId)
        {
            var startMonthParameter = startMonth.HasValue ?
                new ObjectParameter("StartMonth", startMonth) :
                new ObjectParameter("StartMonth", typeof(int));
    
            var endMonthParameter = endMonth.HasValue ?
                new ObjectParameter("EndMonth", endMonth) :
                new ObjectParameter("EndMonth", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetPatmentReport_Result>("Usp_GetPatmentReport", startMonthParameter, endMonthParameter, yearParameter, employeeIdParameter);
        }
    
        public virtual ObjectResult<Usp_EMployeePaymentSummuryReport_Result> Usp_EMployeePaymentSummuryReport(Nullable<long> companyId, Nullable<int> month, Nullable<int> year, Nullable<long> employeeId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(long));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_EMployeePaymentSummuryReport_Result>("Usp_EMployeePaymentSummuryReport", companyIdParameter, monthParameter, yearParameter, employeeIdParameter);
        }
    
        public virtual ObjectResult<Usp_GetAssignedWorkerListWithAttendance_Result> Usp_GetAssignedWorkerListWithAttendance(Nullable<int> companyId, Nullable<int> roleId, Nullable<System.DateTime> date, Nullable<int> siteId, Nullable<long> employeeId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var siteIdParameter = siteId.HasValue ?
                new ObjectParameter("SiteId", siteId) :
                new ObjectParameter("SiteId", typeof(int));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetAssignedWorkerListWithAttendance_Result>("Usp_GetAssignedWorkerListWithAttendance", companyIdParameter, roleIdParameter, dateParameter, siteIdParameter, employeeIdParameter);
        }
    
        public virtual ObjectResult<Usp_GetDateWiseEmployeePaymentReport_Result> Usp_GetDateWiseEmployeePaymentReport(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<long> employeeId)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetDateWiseEmployeePaymentReport_Result>("Usp_GetDateWiseEmployeePaymentReport", startDateParameter, endDateParameter, employeeIdParameter);
        }
    
        public virtual ObjectResult<Usp_GetDateWiseEmployeePaymentReport_dipaktest_Result> Usp_GetDateWiseEmployeePaymentReport_dipaktest(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<long> employeeId)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetDateWiseEmployeePaymentReport_dipaktest_Result>("Usp_GetDateWiseEmployeePaymentReport_dipaktest", startDateParameter, endDateParameter, employeeIdParameter);
        }
    
        public virtual ObjectResult<Usp_GetDateWiseMaterialReport_Result> Usp_GetDateWiseMaterialReport(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<long> materialCategory, Nullable<long> siteId, Nullable<long> companyId)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var materialCategoryParameter = materialCategory.HasValue ?
                new ObjectParameter("MaterialCategory", materialCategory) :
                new ObjectParameter("MaterialCategory", typeof(long));
    
            var siteIdParameter = siteId.HasValue ?
                new ObjectParameter("SiteId", siteId) :
                new ObjectParameter("SiteId", typeof(long));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetDateWiseMaterialReport_Result>("Usp_GetDateWiseMaterialReport", startDateParameter, endDateParameter, materialCategoryParameter, siteIdParameter, companyIdParameter);
        }
    
        public virtual ObjectResult<Usp_GetDateWiseWorkerPaymentReport_Result> Usp_GetDateWiseWorkerPaymentReport(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<long> employeeId)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetDateWiseWorkerPaymentReport_Result>("Usp_GetDateWiseWorkerPaymentReport", startDateParameter, endDateParameter, employeeIdParameter);
        }
    
        public virtual ObjectResult<Usp_GetPaymentReport_Result> Usp_GetPaymentReport(Nullable<int> startMonth, Nullable<int> endMonth, Nullable<int> year, Nullable<long> employeeId)
        {
            var startMonthParameter = startMonth.HasValue ?
                new ObjectParameter("StartMonth", startMonth) :
                new ObjectParameter("StartMonth", typeof(int));
    
            var endMonthParameter = endMonth.HasValue ?
                new ObjectParameter("EndMonth", endMonth) :
                new ObjectParameter("EndMonth", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetPaymentReport_Result>("Usp_GetPaymentReport", startMonthParameter, endMonthParameter, yearParameter, employeeIdParameter);
        }
    
        public virtual ObjectResult<Usp_GetSiteAssignedWorkerList_Result> Usp_GetSiteAssignedWorkerList(Nullable<long> companyId, Nullable<int> roleId, Nullable<long> siteId, Nullable<System.DateTime> date)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(long));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var siteIdParameter = siteId.HasValue ?
                new ObjectParameter("SiteId", siteId) :
                new ObjectParameter("SiteId", typeof(long));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetSiteAssignedWorkerList_Result>("Usp_GetSiteAssignedWorkerList", companyIdParameter, roleIdParameter, siteIdParameter, dateParameter);
        }
    
        public virtual ObjectResult<Usp_WorkerPaymentSummuryReport_Result> Usp_WorkerPaymentSummuryReport(Nullable<long> companyId, Nullable<int> month, Nullable<int> year, Nullable<long> employeeId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(long));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_WorkerPaymentSummuryReport_Result>("Usp_WorkerPaymentSummuryReport", companyIdParameter, monthParameter, yearParameter, employeeIdParameter);
        }
    }
}
