//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_FinancialYear
    {
        public long FinancialYearId { get; set; }
        public int StartYear { get; set; }
        public int EndYear { get; set; }
        public string FinancialYearText { get; set; }
    }
}
