//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CompanySMSPackRenew
    {
        public long CompanySMSPackRenewId { get; set; }
        public long CompanyId { get; set; }
        public long SMSPackageId { get; set; }
        public string SMSPackageName { get; set; }
        public System.DateTime RenewDate { get; set; }
        public int AccessDays { get; set; }
        public System.DateTime PackageExpiryDate { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
