//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Conversion
    {
        public long ConversionId { get; set; }
        public System.DateTime DateOfConversion { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public long CompanyId { get; set; }
        public long CreatedBy { get; set; }
    }
}
