//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Material
    {
        public long MaterialId { get; set; }
        public long CompanyId { get; set; }
        public Nullable<long> MaterialCategoryId { get; set; }
        public System.DateTime MaterialDate { get; set; }
        public long SiteId { get; set; }
        public decimal Qty { get; set; }
        public int InOut { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> FinancialYearId { get; set; }
        public Nullable<bool> IsYearlyConversionEntry { get; set; }
    }
}
