//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmployeeBuyTransaction
    {
        public long EmployeeBuyTransactionId { get; set; }
        public long CompanyId { get; set; }
        public int NoOfEmpToBuy { get; set; }
        public int Days { get; set; }
        public decimal AmountPerEmp { get; set; }
        public decimal TotalPaidAmount { get; set; }
        public Nullable<decimal> GSTPer { get; set; }
        public Nullable<long> FinancialYearId { get; set; }
        public string PaymentGatewayTransactionId { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
