//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SMSPackage
    {
        public long SMSPackageId { get; set; }
        public string PackageName { get; set; }
        public string PackageImage { get; set; }
        public decimal PackageAmount { get; set; }
        public int AccessDays { get; set; }
        public int NoOfSMS { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string PackageColorCode { get; set; }
        public string PackageFontIcon { get; set; }
    }
}
