//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmployeeRating
    {
        public long EmployeeRatingId { get; set; }
        public long EmployeeId { get; set; }
        public int RateMonth { get; set; }
        public int RateYear { get; set; }
        public decimal BehaviourRate { get; set; }
        public decimal RegularityRate { get; set; }
        public decimal WorkRate { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
