//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CompanyFollowup
    {
        public long CompanyFollowupId { get; set; }
        public long CompanyId { get; set; }
        public System.DateTime FollowupDate { get; set; }
        public string FollowupText { get; set; }
        public string Remarks { get; set; }
        public int FollowupStatus { get; set; }
        public Nullable<System.DateTime> NextDate { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
