//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Company
    {
        public long CompanyId { get; set; }
        public long CompanyTypeId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyCode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string GSTNo { get; set; }
        public string GSTPhoto { get; set; }
        public string CompanyPhoto { get; set; }
        public string CancellationChequePhoto { get; set; }
        public string RequestStatus { get; set; }
        public string RejectReason { get; set; }
        public int FreeAccessDays { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
