//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CompanyRenewPayment
    {
        public long CompanyRegistrationPaymentId { get; set; }
        public long CompanyId { get; set; }
        public long PackageId { get; set; }
        public string PackageName { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal Amount { get; set; }
        public decimal GSTPer { get; set; }
        public int AccessDays { get; set; }
        public int NoOfEmployee { get; set; }
        public int NoOfSMS { get; set; }
        public string PaymentFor { get; set; }
        public string PaymentGatewayResponseId { get; set; }
        public int BuyNoOfEmployee { get; set; }
        public string InvoiceNo { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
