//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Company
    {
        public long CompanyId { get; set; }
        public long CompanyTypeId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyCode { get; set; }
        public string EmailId { get; set; }
        public string ContactNo { get; set; }
        public string AlternateContactNo { get; set; }
        public string Address { get; set; }
        public string Pincode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public Nullable<long> StateId { get; set; }
        public Nullable<long> DistrictId { get; set; }
        public string GSTNo { get; set; }
        public string GSTPhoto { get; set; }
        public string PanNo { get; set; }
        public string PanPhoto { get; set; }
        public string CompanyLogoImage { get; set; }
        public string RegisterProofImage { get; set; }
        public string Description { get; set; }
        public string WebisteUrl { get; set; }
        public int FreeAccessDays { get; set; }
        public bool IsTrialMode { get; set; }
        public Nullable<System.DateTime> TrialExpiryDate { get; set; }
        public Nullable<long> CurrentPackageId { get; set; }
        public Nullable<System.DateTime> AccountStartDate { get; set; }
        public Nullable<System.DateTime> AccountExpiryDate { get; set; }
        public Nullable<int> CurrentEmployeeAccess { get; set; }
        public Nullable<int> RemainingEmployeeAccess { get; set; }
        public Nullable<int> CurrentSMSPackageId { get; set; }
        public Nullable<System.DateTime> SMSPackStartDate { get; set; }
        public Nullable<System.DateTime> SMSPackExpiryDate { get; set; }
        public Nullable<int> TotalSMSReceived { get; set; }
        public Nullable<int> RemainingSMSToUse { get; set; }
        public Nullable<System.DateTime> NextFollowupDate { get; set; }
        public Nullable<int> FollowupStatus { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> NoOfLunchBreakAllowed { get; set; }
        public string SiteLocationAccessPassword { get; set; }
        public string OfficeLocationAccessPassword { get; set; }
        public Nullable<int> CompanyConversionType { get; set; }
    }
}
