//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmployeeFingerprint
    {
        public long EmployeeFingerprintId { get; set; }
        public long EmployeeId { get; set; }
        public string ISOCode { get; set; }
        public string BitmapCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
